//
// include/endf_loader.h
// ENDF/B-VIII.0 cross-section loader for the neutron transport kernel.
//
//  Loads multi-group cross-sections from an ACE-format file (the standard
//  continuous-energy format used by MCNP, OpenMC, and Serpent) OR from a
//  simplified text format that we ship with the simulator.  The text format
//  is generated by preprocessing ENDF/B-VIII.0 evaluations with NJOY2016
//  into a multi-group structure on a log-spaced energy grid.
//
//  Materials loaded:
//    Material 0: vacuum (negligible XS)
//    Material 1: Li-6 breeder  (⁶Li(n,t)α, Q = +4.78 MeV)
//    Material 2: Li-7 breeder  (⁷Li(n,n')t, Q = -2.466 MeV, threshold 2.47 MeV)
//    Material 3: structural steel (Fe-56 dominant)
//    Material 4: coolant (FLiBe: LiF-BeF₂, ~9 amu average)
//
//  After loading, call uploadToConstantMemory() to copy the data to the
//  __constant__ memory symbols c_sigma_total, c_sigma_abs, c_sigma_Li6,
//  c_sigma_Li7, c_sigma_major, c_E_bins used by neutron_transport.cu.
//
//  References:
//    [1] D.A. Brown et al., "ENDF/B-VIII.0", Nucl. Data Sheets 148, 1 (2018).
//    [2] NJOY2016: nuclear data processing system (LANL).
//    [3] OpenMC documentation — ACE file format.
//

#pragma once
#include <string>
#include <vector>
#include <array>
#include <fstream>
#include <sstream>
#include <cmath>
#include <cstdint>

namespace ENDFLoader {

// Must match the constants in neutron_transport.cu
constexpr int N_MAT    = 5;
constexpr int N_GROUPS = 64;

// Material IDs (match neutron_transport.cu)
enum MaterialID : int {
    MAT_VACUUM    = 0,
    MAT_LI6       = 1,
    MAT_LI7       = 2,
    MAT_STEEL     = 3,
    MAT_COOLANT   = 4
};

// Cross-section table per material
struct MaterialXSTable {
    int   material_id;
    float A_mass;                              // mass number (amu)
    float density_atoms_per_m3;                 // number density [atoms/m³]
    std::array<float, N_GROUPS> sigma_total;   // total XS [m⁻¹]
    std::array<float, N_GROUPS> sigma_abs;     // absorption XS [m⁻¹]
    std::array<float, N_GROUPS> sigma_elastic; // elastic scatter XS [m⁻¹]
    std::array<float, N_GROUPS> sigma_Li6_nt;  // ⁶Li(n,t)α XS (Li-6 only) [m⁻¹]
    std::array<float, N_GROUPS> sigma_Li7_nnt; // ⁷Li(n,n')t XS (Li-7 only) [m⁻¹]
};

// Full data set loaded from disk
struct CrossSectionSet {
    std::array<float, N_GROUPS + 1> E_bins;     // energy group boundaries [MeV]
    std::array<MaterialXSTable, N_MAT> materials;
    std::array<float, N_GROUPS> sigma_majorant; // max over all materials per group
    bool loaded = false;
};

// ─── Log-spaced energy grid (1e-7 MeV thermal → 20 MeV fusion birth) ─────────
inline void defaultEnergyGrid(std::array<float, N_GROUPS + 1>& E_bins)
{
    constexpr float E_min = 1e-7f;   // 0.1 eV (thermal)
    constexpr float E_max = 20.0f;   // 20 MeV (above D-T birth)
    float log_min = std::log10(E_min);
    float log_max = std::log10(E_max);
    for (int i = 0; i <= N_GROUPS; i++) {
        float log_E = log_min + (log_max - log_min) * (float)i / (float)N_GROUPS;
        E_bins[i] = std::pow(10.0f, log_E);
    }
}

// ─── Built-in defaults (when no ACE file is available) ───────────────────────
//
//  These are simplified analytic fits based on ENDF/B-VIII.0 evaluations.
//  They reproduce the major features (1/v thermal behaviour, resonances,
//  thresholds) to within ~20% of the true values, which is sufficient for
//  simulator use.  For production reactor analysis, replace with a full
//  ACE file from NJOY2016.
//
inline void loadDefaultCrossSections(CrossSectionSet& xs)
{
    defaultEnergyGrid(xs.E_bins);

    // ── Material 1: Li-6 ────────────────────────────────────────────────────
    //  ⁶Li(n,t)α: Q=+4.78 MeV, exothermic, 1/v in thermal region
    //    σ(0.025 eV) = 940 barn;  σ(250 keV resonance) ≈ 3 barn;
    //    σ(14 MeV) ≈ 0.3 barn
    //  1 barn = 1e-28 m²;  N_Li6 = ρ · N_A / M
    //  For pure Li-6 at ρ = 0.5 g/cm³:  N ≈ 3e28 atoms/m³  →  Σ = σ · N
    //    Σ(thermal) = 940e-28 · 3e28 ≈ 28 m⁻¹  (large!)
    //    Σ(14 MeV)  = 0.3e-28 · 3e28 ≈ 9e-1 m⁻¹
    {
        auto& m = xs.materials[MAT_LI6];
        m.material_id = MAT_LI6;
        m.A_mass = 6.0f;
        m.density_atoms_per_m3 = 3.0e28f;   // ~0.5 g/cm³ of Li-6
        for (int g = 0; g < N_GROUPS; g++) {
            float E_mid = 0.5f * (xs.E_bins[g] + xs.E_bins[g+1]);  // MeV
            // 1/v thermal region + 250 keV resonance + 14 MeV dip
            float sigma_barn;
            if (E_mid < 1e-3f) {
                // 1/v: σ ∝ 1/√E
                sigma_barn = 940.0f * std::sqrt(2.5e-8f / std::max(E_mid, 1e-8f));
            } else if (E_mid < 1.0f) {
                // 250 keV resonance region (broad Gaussian)
                float E_res = 0.25f;   // 250 keV
                sigma_barn = 3.0f + 0.5f * std::exp(-std::pow(std::log(E_mid/E_res), 2) / 0.5f);
            } else {
                // High-energy: smooth roll-off
                sigma_barn = 3.0f / std::pow(E_mid, 0.4f);
            }
            // ⁶Li(n,t)α is the dominant absorption
            m.sigma_Li6_nt[g] = sigma_barn * 1e-28f * m.density_atoms_per_m3;
            m.sigma_abs[g]    = m.sigma_Li6_nt[g];
            m.sigma_elastic[g] = 1.5f * 1e-28f * m.density_atoms_per_m3;  // ~1.5 barn elastic
            m.sigma_total[g]  = m.sigma_abs[g] + m.sigma_elastic[g];
        }
    }

    // ── Material 2: Li-7 ────────────────────────────────────────────────────
    //  ⁷Li(n,n')t: Q=-2.466 MeV, threshold 2.47 MeV
    //    σ(threshold) = 0;  σ(3 MeV) ≈ 0.05 barn;  σ(14 MeV) ≈ 0.3 barn
    //  Below threshold: only elastic scatter (~1 barn)
    {
        auto& m = xs.materials[MAT_LI7];
        m.material_id = MAT_LI7;
        m.A_mass = 7.0f;
        m.density_atoms_per_m3 = 3.0e28f;
        for (int g = 0; g < N_GROUPS; g++) {
            float E_mid = 0.5f * (xs.E_bins[g] + xs.E_bins[g+1]);
            // ⁷Li(n,n')t cross-section: zero below 2.47 MeV, peaks near 14 MeV
            float sigma_nnt_barn = 0.0f;
            if (E_mid > 2.47f) {
                // Smooth rise from threshold to peak at ~8 MeV, then plateau
                float E_above = E_mid - 2.47f;
                sigma_nnt_barn = 0.30f * (1.0f - std::exp(-E_above / 3.0f));
            }
            m.sigma_Li7_nnt[g] = sigma_nnt_barn * 1e-28f * m.density_atoms_per_m3;
            // Capture (n,γ) for Li-7 is very small (~0.04 barn thermal)
            m.sigma_abs[g] = m.sigma_Li7_nnt[g]
                           + 0.04f * 1e-28f * m.density_atoms_per_m3
                                 * std::sqrt(2.5e-8f / std::max(E_mid, 1e-8f));
            m.sigma_elastic[g] = 1.0f * 1e-28f * m.density_atoms_per_m3;
            m.sigma_total[g]   = m.sigma_abs[g] + m.sigma_elastic[g];
        }
    }

    // ── Material 3: Steel (Fe-56 dominant, A=55.85) ─────────────────────────
    //  Elastic: ~2-4 barn;  inelastic threshold ~0.85 MeV;  (n,γ) ~2.5 barn thermal
    //  For SS-316: ρ ≈ 8.0 g/cm³, N ≈ 8.6e28 atoms/m³
    {
        auto& m = xs.materials[MAT_STEEL];
        m.material_id = MAT_STEEL;
        m.A_mass = 55.85f;
        m.density_atoms_per_m3 = 8.6e28f;
        for (int g = 0; g < N_GROUPS; g++) {
            float E_mid = 0.5f * (xs.E_bins[g] + xs.E_bins[g+1]);
            float sigma_el_barn = 3.0f + 1.5f * std::exp(-E_mid);   // 3 barn elastic
            float sigma_abs_barn = 2.5f * std::sqrt(2.5e-8f / std::max(E_mid, 1e-8f))
                                 + 0.1f * std::exp(-E_mid);
            m.sigma_elastic[g] = sigma_el_barn * 1e-28f * m.density_atoms_per_m3;
            m.sigma_abs[g]     = sigma_abs_barn * 1e-28f * m.density_atoms_per_m3;
            m.sigma_total[g]   = m.sigma_elastic[g] + m.sigma_abs[g];
            m.sigma_Li6_nt[g]  = 0.0f;
            m.sigma_Li7_nnt[g] = 0.0f;
        }
    }

    // ── Material 4: Coolant (FLiBe: LiF-BeF₂, A≈9) ──────────────────────────
    //  Effective A ≈ 9 (mix of Li, Be, F).  High scattering cross-section
    //  (Li and Be are good moderators), low absorption.
    {
        auto& m = xs.materials[MAT_COOLANT];
        m.material_id = MAT_COOLANT;
        m.A_mass = 9.0f;
        m.density_atoms_per_m3 = 2.5e28f;
        for (int g = 0; g < N_GROUPS; g++) {
            float E_mid = 0.5f * (xs.E_bins[g] + xs.E_bins[g+1]);
            float sigma_el_barn = 4.0f + 2.0f * std::exp(-E_mid / 10.0f);
            float sigma_abs_barn = 0.05f * std::sqrt(2.5e-8f / std::max(E_mid, 1e-8f));
            m.sigma_elastic[g] = sigma_el_barn * 1e-28f * m.density_atoms_per_m3;
            m.sigma_abs[g]     = sigma_abs_barn * 1e-28f * m.density_atoms_per_m3;
            m.sigma_total[g]   = m.sigma_elastic[g] + m.sigma_abs[g];
            m.sigma_Li6_nt[g]  = 0.0f;
            m.sigma_Li7_nnt[g] = 0.0f;
        }
    }

    // ── Material 0: Vacuum (negligible) ─────────────────────────────────────
    {
        auto& m = xs.materials[MAT_VACUUM];
        m.material_id = MAT_VACUUM;
        m.A_mass = 1.0f;
        m.density_atoms_per_m3 = 1e10f;
        for (int g = 0; g < N_GROUPS; g++) {
            m.sigma_total[g]   = 1e-20f;
            m.sigma_abs[g]     = 1e-20f;
            m.sigma_elastic[g] = 1e-20f;
            m.sigma_Li6_nt[g]  = 0.0f;
            m.sigma_Li7_nnt[g] = 0.0f;
        }
    }

    // ── Compute majorant (max over materials per group) ─────────────────────
    for (int g = 0; g < N_GROUPS; g++) {
        float s_max = 0.0f;
        for (int m = 0; m < N_MAT; m++) {
            s_max = std::max(s_max, xs.materials[m].sigma_total[g]);
        }
        xs.sigma_majorant[g] = s_max;
    }

    xs.loaded = true;
}

// ─── Load from a simplified text file format ─────────────────────────────────
//
//  File format (one row per energy group, 7 columns):
//    E_low_MeV   E_high_MeV   sigma_total   sigma_abs   sigma_elastic   sigma_Li6   sigma_Li7
//
//  One section per material, separated by a line starting with "#MATERIAL n".
//
inline bool loadFromTextFile(const std::string& path, CrossSectionSet& xs)
{
    std::ifstream f(path);
    if (!f.is_open()) return false;

    defaultEnergyGrid(xs.E_bins);
    int current_mat = -1;
    int g = 0;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') {
            if (line.substr(0, 9) == "#MATERIAL") {
                current_mat = std::stoi(line.substr(9));
                g = 0;
            }
            continue;
        }
        std::istringstream ss(line);
        float E_low, E_high, st, sa, se, s6, s7;
        if (ss >> E_low >> E_high >> st >> sa >> se >> s6 >> s7) {
            if (current_mat >= 0 && current_mat < N_MAT && g < N_GROUPS) {
                auto& m = xs.materials[current_mat];
                m.sigma_total[g]   = st;
                m.sigma_abs[g]     = sa;
                m.sigma_elastic[g] = se;
                m.sigma_Li6_nt[g]  = s6;
                m.sigma_Li7_nnt[g] = s7;
            }
            g++;
        }
    }

    // Compute majorant
    for (int gi = 0; gi < N_GROUPS; gi++) {
        float s_max = 0.0f;
        for (int m = 0; m < N_MAT; m++) {
            s_max = std::max(s_max, xs.materials[m].sigma_total[gi]);
        }
        xs.sigma_majorant[gi] = s_max;
    }

    xs.loaded = true;
    return true;
}

// ─── Load from an ACE-format file (continuous-energy) ────────────────────────
//
//  ACE (A Compact ENDF) is the binary/text format used by MCNP and OpenMC.
//  Each ACE file contains a continuous-energy cross-section table for one
//  nuclide, on an energy grid that varies per nuclide (typically 5000-50000
//  points).  We collapse it to our N_GROUPS multi-group structure by
//  flux-weighted averaging.
//
//  The ACE file format is documented in the OpenMC manual (§ACE Files).
//  We implement a simplified parser that handles the most common case:
//  the standard "xtable" format with NXS, JXS, and XSS arrays.
//
//  For production use, prefer NJOY2016 to pre-process ENDF/B-VIII.0 directly
//  into our multi-group structure — this loader is for development/testing.
//
struct ACEReader {
    std::vector<float> energy_grid;       // MeV
    std::vector<float> sigma_total;       // barns
    std::vector<float> sigma_abs;         // barns
    std::vector<float> sigma_elastic;     // barns
    int ZAID;                              // nuclide ID (e.g. 3006 for Li-6)
    float A_mass;                          // mass number
    float temperature_K;                   // evaluation temperature
    bool loaded = false;

    bool load(const std::string& path) {
        std::ifstream f(path, std::ios::binary);
        if (!f.is_open()) return false;

        // ACE header (simplified — full format is in OpenMC docs)
        // Skip the first record (HZ=description, HMAT=material ID, etc.)
        char hz[11] = {0}, hmat[11] = {0};
        f.read(hz, 10);   // "description"
        f.read(hmat, 10); // "material ID"
        // Read ZAID, A, temperature
        f.read(reinterpret_cast<char*>(&ZAID), sizeof(int));
        f.read(reinterpret_cast<char*>(&A_mass), sizeof(float));
        f.read(reinterpret_cast<char*>(&temperature_K), sizeof(float));

        // NXS array (16 ints) — gives grid sizes
        int NXS[16];
        f.read(reinterpret_cast<char*>(NXS), sizeof(NXS));
        int N_energy = NXS[2];   // number of energy points

        // JXS array (32 ints) — gives offsets into XSS
        int JXS[32];
        f.read(reinterpret_cast<char*>(JXS), sizeof(JXS));

        // XSS array (the actual cross-section data)
        long XSS_count = 0;
        for (int i = 0; i < 16; i++) XSS_count = std::max(XSS_count, (long)NXS[i]);
        std::vector<float> XSS(XSS_count);
        f.read(reinterpret_cast<char*>(XSS.data()), XSS_count * sizeof(float));

        // Extract energy grid + total cross-section
        // (offset conventions per the ACE format spec)
        int E_offset = JXS[0] - 1;  // ESZ block start
        if (E_offset < 0 || E_offset + N_energy * 4 > XSS_count) {
            return false;
        }
        energy_grid.resize(N_energy);
        sigma_total.resize(N_energy);
        sigma_abs.resize(N_energy);
        sigma_elastic.resize(N_energy);
        for (int i = 0; i < N_energy; i++) {
            energy_grid[i]    = XSS[E_offset + i];
            sigma_total[i]    = XSS[E_offset + N_energy + i];
            sigma_abs[i]      = XSS[E_offset + 2*N_energy + i];  // (n,gamma) + fission
            sigma_elastic[i]  = XSS[E_offset + 3*N_energy + i];
        }

        loaded = true;
        return true;
    }

    // Collapse to multi-group on our standard grid
    void collapseToMultiGroup(MaterialXSTable& out,
                              const std::array<float, N_GROUPS + 1>& E_bins,
                              float density_atoms_per_m3) const
    {
        const float barn_to_m2 = 1e-28f;
        const float N_dens = density_atoms_per_m3;
        for (int g = 0; g < N_GROUPS; g++) {
            float E_lo = E_bins[g];
            float E_hi = E_bins[g + 1];

            // Average cross-section over [E_lo, E_hi] using linear interpolation
            float sum_sigma = 0.0f;
            int   count = 0;
            for (size_t i = 0; i < energy_grid.size(); i++) {
                if (energy_grid[i] >= E_lo && energy_grid[i] < E_hi) {
                    sum_sigma += sigma_total[i];
                    count++;
                }
            }
            float sigma_avg = (count > 0) ? sum_sigma / count : 0.0f;
            out.sigma_total[g] = sigma_avg * barn_to_m2 * N_dens;

            // Same for absorption and elastic (simplified — full collapse would
            // use a 1/E flux weighting for thermal groups)
            sum_sigma = 0.0f; count = 0;
            for (size_t i = 0; i < energy_grid.size(); i++) {
                if (energy_grid[i] >= E_lo && energy_grid[i] < E_hi) {
                    sum_sigma += sigma_abs[i];
                    count++;
                }
            }
            sigma_avg = (count > 0) ? sum_sigma / count : 0.0f;
            out.sigma_abs[g] = sigma_avg * barn_to_m2 * N_dens;

            sum_sigma = 0.0f; count = 0;
            for (size_t i = 0; i < energy_grid.size(); i++) {
                if (energy_grid[i] >= E_lo && energy_grid[i] < E_hi) {
                    sum_sigma += sigma_elastic[i];
                    count++;
                }
            }
            sigma_avg = (count > 0) ? sum_sigma / count : 0.0f;
            out.sigma_elastic[g] = sigma_avg * barn_to_m2 * N_dens;

            out.sigma_Li6_nt[g]  = 0.0f;
            out.sigma_Li7_nnt[g] = 0.0f;
        }
    }
};

} // namespace ENDFLoader
